# kind-clusters.yaml

# --- Configuración para el clúster de STAGING ---
# Solo este necesita el puerto expuesto para pruebas locales.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: staging
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8081
---
# --- Configuración para el clúster de PRODUCCIÓN EAST ---
# Este no necesita exponer puertos en el host para este tutorial.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: prod-east
---
# --- Configuración para el clúster de PRODUCCIÓN WEST ---
# Este tampoco necesita exponer puertos en el host.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: prod-west